FROM mcr.microsoft.com/devcontainers/go:1-1.21-bullseye

WORKDIR /monkey

COPY . .

# monkeyコマンドにパスを通す
RUN echo "export PATH=$HOME/workspaces/monkey/moneky:$PATH" >> ~/.bash_profile
RUN sudo ln -si /workspaces/monkey/monkey /usr/local/bin/monkey